[package]
name = "rustvillage"
version = "0.1.0"
edition = "2021"

[dependencies]
#bevy = { version = "0.15.0", features = ["dynamic_linking"] }
bevy = { version = "0.15.0" }
bevy_atmosphere = "0.12.2"
grid_pathfinding = "0.2.1"
grid_util = "0.1.1"
leafwing-input-manager = "0.16.0"
moonshine-core = "0.2.1"
moonshine-object = "0.2.1"
moonshine-view = "0.1.6"
noisy_bevy = "0.8.0"
rand = "0.8.5"

[profile.dev.package."*"]
opt-level = 3
