[package]
name = "rustvillage"
version = "0.1.0"
edition = "2021"

[dependencies]
#bevy = { version = "0.15.0", features = ["dynamic_linking"] }
bevy = { version = "0.15.0" }
leafwing-input-manager = "0.16.0"
rand = "0.8.5"